/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import color from './color';
import commerce from './commerce';
import date from './date';
import location from './location';
import lorem from './lorem';
import person from './person';
import team from './team';

/**
 * The locale data for the `ar` locale.
 *
 * - Language: Arabic
 * - Endonym: اَلْعَرَبِيَّةُ
 */
const ar: LocaleDefinition = {
  cell_phone,
  color,
  commerce,
  date,
  location,
  lorem,
  person,
  team,
};

export default ar;
