/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import base from './base';
import en from './en';
import ja from './ja';
import vi from './vi';
import zh_CN from './zh_CN';
import ar from './ar';
import de from './de';
import es from './es';
import fr from './fr';
import ko from './ko';
import pl from './pl';
import ru from './ru';

export { default as base } from './base';
export { default as en } from './en';
export { default as ja } from './ja';
export { default as vi } from './vi';
export { default as zh_CN } from './zh_CN';
export { default as ar } from './ar';
export { default as de } from './de';
export { default as es } from './es';
export { default as fr } from './fr';
export { default as ko } from './ko';
export { default as pl } from './pl';
export { default as ru } from './ru';

export const allLocales = {
  base,
  en,
  ja,
  vi,
  zh_CN,
  ar,
  de,
  es,
  fr,
  ko,
  pl,
  ru,
} as const;
