/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import cell_phone from './cell_phone';
import color from './color';
import company from './company';
import date from './date';
import finance from './finance';
import internet from './internet';
import location from './location';
import lorem from './lorem';
import person from './person';
import phone_number from './phone_number';
import team from './team';
import word from './word';

/**
 * The locale data for the `en` locale.
 *
 * - Language: English
 * - Endonym: English
 */
const en: LocaleDefinition = {
  cell_phone,
  color,
  company,
  date,
  finance,
  internet,
  location,
  lorem,
  person,
  phone_number,
  team,
  word,
};

export default en;
