/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { InternetDefinition } from '../../..';
import http_status_code from './http_status_code';
import user_agent_pattern from './user_agent_pattern';

const internet: InternetDefinition = {
  http_status_code,
  user_agent_pattern,
};

export default internet;
