/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { faker as fakerBASE } from './base';
import { faker as fakerEN } from './en';
import { faker as fakerJA } from './ja';
import { faker as fakerVI } from './vi';
import { faker as fakerZH_CN } from './zh_CN';
import { faker as fakerAR } from './ar';
import { faker as fakerDE } from './de';
import { faker as fakerES } from './es';
import { faker as fakerFR } from './fr';
import { faker as fakerKO } from './ko';
import { faker as fakerPL } from './pl';
import { faker as fakerRU } from './ru';

export { faker as fakerBASE } from './base';
export { faker as fakerEN } from './en';
export { faker as fakerJA } from './ja';
export { faker as fakerVI } from './vi';
export { faker as fakerZH_CN } from './zh_CN';
export { faker as fakerAR } from './ar';
export { faker as fakerDE } from './de';
export { faker as fakerES } from './es';
export { faker as fakerFR } from './fr';
export { faker as fakerKO } from './ko';
export { faker as fakerPL } from './pl';
export { faker as fakerRU } from './ru';


export const allFakers = {
  base: fakerBASE,
  en: fakerEN,
  ja: fakerJA,
  vi: fakerVI,
  zh_CN: fakerZH_CN,
  ar: fakerAR,
  de: fakerDE,
  es: fakerES,
  fr: fakerFR,
  ko: fakerKO,
  pl: fakerPL,
  ru: fakerRU,
} as const;
