/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import color from './color';
import date from './date';
import internet from './internet';
import location from './location';
import system from './system';

/**
 * The locale data for the `base` locale.
 *
 * The base locale contains data that is shared across all locales such as ISO codes, time zones, and more.
 */
const base: LocaleDefinition = {
  color,
  date,
  internet,
  location,
  system,
};

export default base;
