/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LoremDefinition } from '../../..';
import word from './word';
import sentence from './sentence';

const lorem: LoremDefinition = {
  word,
  sentence,
};

export default lorem;
