/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import color from './color';
import company from './company';
import date from './date';
import finance from './finance';
import internet from './internet';
import location from './location';
import person from './person';
import phone_number from './phone_number';
import word from './word';

/**
 * The locale data for the `zh_CN` locale.
 *
 * - Language: Chinese (China)
 * - Endonym: 中文 (中国)
 */
const zh_CN: LocaleDefinition = {
  color,
  company,
  date,
  finance,
  internet,
  location,
  person,
  phone_number,
  word,
};

export default zh_CN;
